- package.json
- telegram_dispatch.js
Massive refactoring of telegram_dispatch due to library change. 
EMA + SMA signals are parsed and pushed to telegram.
> [SQS] New branch

- package.json
@Brbb please review and merge if acceptable. thx
> remove claudia.js dependancy

- package.json
- signal_producer.js
- telegram_dispatch.js
- test/t_push_signal.js
> Merge duplicate signals fix into release-production

- telegram.js
- telegram_dispatch.js
- util/error.js
Merge some minor fixes like text format, wrong labels, unhandled rejections.
> Minor fixes

- commands/signal_helper.js
- db/storage.js
- telegram_dispatch.js
- util/extensions.js
This feature checks if the message is valid (`send_at < 15 * 60000`) and formats the signal message in order to provide all the signal related info (close #18)
> Skip signals older than 15 minutes

- commands/signal_helper.js
Horizon now is a number from 0 to 2
> [SQS] Refactoring horizon parsing

- commands/price.js
- commands/signal_helper.js
Horizon is now 0 to 2 as "short" to "long".
> Horizon parsing refactoring

- commands/signal_helper.js
Removing 15 minutes control to check if the expiration date check has
conversion problems
> Remove expiration control

- commands/signal_helper.js
- telegram_dispatch.js
Add functionalities to close #20
> Filter by user settings

- commands/signal_helper.js
Minor styling fixes and refactoring
> [SQS] Signal text style

- commands/settings.js
Added console logs for debugging purposes
> [Token][Debug]

- commands/signal_helper.js
- telegram_dispatch.js
New RSI signal parsing and telegram message template composition. Need to test with real RSI to tune.
Close #67
> [Signal] RSI

- commands/keyboards/coins.js
- commands/keyboards/exchange.js
- commands/keyboards/main.js
- commands/settings.js
- buttons load performance improved
- code clean up
- added quota currency menu (Edit signals)
- embedded altcoins list in Edit Signals
close #73
> [Settings] Edit Signals + Altcoins menu

- commands/keyboards/coins.js
- commands/keyboards/exchange.js
- forgot an env variable 🐐
- added a dummy initialisation
> [Settings] Env fix

- commands/signal_helper.js
RSI is sending rsi_value as string, but the bot was not processing it
correctly.
> [Signal]RSI fix

- telegram.js
> [Feedback] fix on backend might need redeploy

- .gitignore
- commands/feedback.js
- package.json
- telegram.js
Added username to feedback for easy contact
> [Feedback] Improvements

- commands/data/tickers.js
- commands/keyboards/coins.js
- core/api.js
- package.json
- telegram.js
- Telegram Bot loads the tickers from its-node-services and caches the
list client side at init time.
> [Settings] Coins caching

- commands/price.js
- telegram.js
- cached tickers provide the full name of the coin to build the full
url of the same and redirect on click to CoinmarketCap.
- the link is in the shortcode of the coin (ETH,BTC, etc)
close #53
> [Commands] Price has a link to a wiki

- commands/data/tickers.js
- commands/feedback.js
Added the `/api` path to use an `API_KEY` without affecting the html
pages (the EULA)
> [API] Node services

- commands/data/tickers.js
- core/api.js
API for node services require a KEY and a different address
> [API] Adder tickersInfo api

- commands/keyboards/main.js
- Moved extra buttons to buttons available for all the users
- Risk is now hidden for everybody
> [Settings] Buttons

- commands/keyboards/currencies.js
- commands/keyboards/exchange.js
- commands/keyboards/keyboard.js
- commands/keyboards/main.js
- commands/keyboards/trader.js
- commands/settings.js
- telegram.js
- fixed subscribe message
- fixed Edit Signals button
- added Close button for the main menu
> [Fix] Text and buttons fixes

- commands/price.js
- commands/signal_helper.js
- core/api.js
- telegram_dispatch.js
From coin to the proper definition of counter/transaction currency
> Coin to currency api

- commands/data/tickers.js
- commands/price.js
- commands/signal_helper.js
It seems like the node services sometimes gets stuck and the price
gives error, it might be for some hanging Promise or exception, but
this blocks signals (probably), so it’s better to filter and give an
empty coinmarketcap link.
> [Command] Price

- commands/signal_helper.js
- telegram_dispatch.js
All the counter currencies signals are now dispatched to all the users
> [Signals] Removed isBitcoin filter

- commands/data/tickers.js
- commands/keyboards/currencies.js
- commands/keyboards/exchange.js
- commands/keyboards/main.js
- commands/settings.js
- commands/signal_helper.js
- core/api.js
- telegram_dispatch.js
- counter currencies API call
- transaction currencies API call
- better dispatcher
- dynamic filters without multiple API queue
close #6 #108
> Api refactoring

- commands/data/tickers.js
- commands/keyboards/currencies.js
- core/api.js
- telegram.js
closes #124 and fixes Poloniex Coin’s list
> Poloniex and keyboard fix

- commands/settings.js
- core/api.js
- telegram.js
- telegram_dispatch.js
> Access free signals

- commands/settings.js
- telegram.js
- added “apollo” as error message delivery object (thinking about a
separate file for the object)
- fixed the check which was giving subscription to the signals even
without accepting the EULA
> EULA messaging FIX

- commands/signal_helper.js
> RSI restyiling

- commands/controllers/price.js
- commands/controllers/volume.js
- core/api.js
Fixed /volume API backend, still margin of improvement: https://app.asana.com/0/567041585915013/748435713288249/f
Fixed: https://app.asana.com/0/567041585915013/747955394578465/f
> [FIX] Volume and price command had minor bugs to fix.

- util/signal-helper.js
https://app.asana.com/0/567041585915013/673433865536151/f
> [Signals] ANN simple live

- package.json
- telegram.js
https://app.asana.com/0/567041585915013/741243681604076/f
> [BOT] Universal Analytics Tracking

- commands/keyboards/settingsKeyboard.js
- core/api.js
- telegram.js
https://app.asana.com/0/567041585915013/756441058622670/f
> [Feature] Referral code

- commands/controllers/start.js
- commands/keyboards/settingsKeyboard.js
- telegram.js
https://app.asana.com/0/567041585915013/770757834031952/f
> [UI] Referral improvements

- util/signal-helper.js
https://app.asana.com/0/567041585915013/773984316902295/f
> [Improvement] Filter AI signals with probability threshold < 2%

- events/signals.js
https://app.asana.com/0/567041585915013/786497827674873/f
> [FIX] Dispatcher was not filtering signals

- commands/keyboards/basicKeyboard.js
- commands/keyboards/settingsKeyboard.js
https://app.asana.com/0/567041585915013/659381358321442/f
> Ui refactoring
